default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contact

test:
  <<: *default
  database: contact_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: contact_production
  username: contact
  host: localhost
  password: <%= ENV['CONTACT_DATABASE_PASSWORD'] %>
